/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_neandrake_windows_IntegrityProcessLauncher */

#ifndef _Included_net_neandrake_windows_IntegrityProcessLauncher
#define _Included_net_neandrake_windows_IntegrityProcessLauncher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_neandrake_windows_IntegrityProcessLauncher
 * Method:    createProcessWithExplorerIntegrity
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_neandrake_windows_IntegrityProcessLauncher_createProcessWithExplorerIntegrity
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
